# Generated by Django 4.2.29 on 2026-04-02 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dag_id', models.CharField(db_index=True, help_text="The Airflow DAG identifier (e.g. 'etl_daily_sales').", max_length=250, unique=True)),
                ('name', models.CharField(help_text='Human-readable name.', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('python_script', models.TextField(help_text='Full Python source code of the DAG file.')),
                ('schedule_interval', models.CharField(blank=True, default='', help_text="Cron expression or Airflow preset (e.g. '0 2 * * *', '@daily').", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the DAG is enabled (un-paused) in Airflow.')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retries for failed tasks.')),
                ('retry_delay_seconds', models.IntegerField(default=300, help_text='Delay in seconds between retries.')),
                ('timeout_seconds', models.IntegerField(default=3600, help_text='Execution timeout in seconds.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of string tags for categorisation.')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Arbitrary configuration parameters passed to the DAG.')),
                ('owner', models.CharField(blank=True, db_index=True, default='', help_text='Owner identifier (team or individual).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', help_text='Azure AD user who created this DAG.', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', help_text='Azure AD user who last updated this DAG.', max_length=255)),
            ],
            options={
                'verbose_name': 'DAG',
                'verbose_name_plural': 'DAGs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DAGRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(help_text="Airflow's unique run identifier.", max_length=250)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20)),
                ('execution_date', models.DateTimeField(help_text='Logical execution date for the run.')),
                ('start_date', models.DateTimeField(blank=True, help_text='Actual start time.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Actual end time.', null=True)),
                ('external_trigger', models.BooleanField(default=False, help_text='Whether this run was triggered externally.')),
                ('conf', models.JSONField(blank=True, default=dict, help_text='Runtime configuration passed when triggering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dags.dag')),
            ],
            options={
                'verbose_name': 'DAG Run',
                'verbose_name_plural': 'DAG Runs',
                'ordering': ['-execution_date'],
                'unique_together': {('dag', 'run_id')},
            },
        ),
        migrations.CreateModel(
            name='DAGRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='When the log entry was produced.')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('dag_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dags.dagrun')),
            ],
            options={
                'verbose_name': 'DAG Run Log',
                'verbose_name_plural': 'DAG Run Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
