# Generated by Django 4.2.29 on 2026-04-02 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.CharField(db_index=True, help_text='Azure AD user email or OID who performed the action.', max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRIGGER', 'Trigger'), ('PAUSE', 'Pause'), ('UNPAUSE', 'Unpause')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(db_index=True, help_text="Type of resource acted upon (e.g. 'DAG', 'DAGRun').", max_length=100)),
                ('resource_id', models.CharField(db_index=True, help_text='Primary key of the affected resource.', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before/after snapshot of changed fields.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address.', null=True)),
                ('user_agent', models.CharField(blank=True, default='', help_text='Client User-Agent header.', max_length=500)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_efff2a_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx')],
            },
        ),
    ]
